-- =============================================================================
-- Supabase Database Schema
-- AI-Driven Digital Evidence Integrity Monitoring System
-- =============================================================================
-- Copy and paste this script into your Supabase SQL Editor to initialize all tables.
-- =============================================================================

-- 1. Evidence Table — All registered evidence files
CREATE TABLE IF NOT EXISTS public.evidence (
    evidence_id     VARCHAR(32) PRIMARY KEY,
    file_name       TEXT NOT NULL,
    file_path       TEXT NOT NULL,
    file_type       VARCHAR(32) NOT NULL, -- 'image', 'video', 'document'
    file_size       BIGINT NOT NULL,
    hash_value      TEXT NOT NULL,        -- SHA-256 hex digest
    storage_path    TEXT DEFAULT '',      -- Supabase Storage bucket path
    storage_url     TEXT DEFAULT '',      -- Supabase Storage public/signed URL
    uploaded_by     TEXT NOT NULL DEFAULT 'system',
    upload_time     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    status          VARCHAR(32) NOT NULL DEFAULT 'pending' -- 'pending', 'verified', 'approved', 'tampered'
);

-- Add columns if table already exists
ALTER TABLE public.evidence ADD COLUMN IF NOT EXISTS storage_path TEXT DEFAULT '';
ALTER TABLE public.evidence ADD COLUMN IF NOT EXISTS storage_url TEXT DEFAULT '';

-- Index for fast lookup by file_type and status
CREATE INDEX IF NOT EXISTS idx_evidence_file_type ON public.evidence(file_type);
CREATE INDEX IF NOT EXISTS idx_evidence_status ON public.evidence(status);


-- 2. Custody Table — Immutable chain-of-custody audit log
CREATE TABLE IF NOT EXISTS public.custody (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evidence_id     VARCHAR(32) NOT NULL REFERENCES public.evidence(evidence_id) ON DELETE CASCADE,
    action          VARCHAR(32) NOT NULL, -- 'upload', 'verify', 'approve', 'access', 'alert'
    user_name       TEXT NOT NULL DEFAULT 'system',
    timestamp       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    notes           TEXT DEFAULT ''
);

-- Index for custody timeline queries
CREATE INDEX IF NOT EXISTS idx_custody_evidence_id ON public.custody(evidence_id);


-- 3. Tamper Alerts Table — Permanently recorded tampering events
CREATE TABLE IF NOT EXISTS public.tamper_alerts (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evidence_id     VARCHAR(32) NOT NULL,
    file_name       TEXT NOT NULL,
    file_type       VARCHAR(32) NOT NULL,
    stored_hash     TEXT NOT NULL,
    current_hash    TEXT NOT NULL,
    detected_by     TEXT NOT NULL DEFAULT 'system',
    timestamp       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    resolved        BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_tamper_alerts_evidence_id ON public.tamper_alerts(evidence_id);


-- 4. Approvals Table — Officer approvals for blockchain ledger
CREATE TABLE IF NOT EXISTS public.approvals (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evidence_id     VARCHAR(32) NOT NULL REFERENCES public.evidence(evidence_id) ON DELETE CASCADE,
    approved_by     TEXT NOT NULL,
    block_index     INTEGER NOT NULL,
    timestamp       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    notes           TEXT DEFAULT ''
);

CREATE INDEX IF NOT EXISTS idx_approvals_evidence_id ON public.approvals(evidence_id);


-- 5. Reports Table — Full aggregated forensic report payloads (JSONB)
CREATE TABLE IF NOT EXISTS public.reports (
    evidence_id     VARCHAR(32) PRIMARY KEY REFERENCES public.evidence(evidence_id) ON DELETE CASCADE,
    overall_status  VARCHAR(32) NOT NULL, -- 'completed', 'partial', 'failed'
    file_metadata   JSONB NOT NULL,
    blockchain_res  JSONB,
    metadata_res    JSONB,
    forgery_res     JSONB,
    deepfake_res    JSONB,
    fake_news_res   JSONB,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Enable Row Level Security (RLS) - Optional default open policy for local integration
ALTER TABLE public.evidence ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.custody ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tamper_alerts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.approvals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reports ENABLE ROW LEVEL SECURITY;

-- Default permissive RLS policies for anon/authenticated roles
CREATE POLICY "Allow all access to evidence" ON public.evidence FOR ALL USING (true);
CREATE POLICY "Allow all access to custody" ON public.custody FOR ALL USING (true);
CREATE POLICY "Allow all access to tamper_alerts" ON public.tamper_alerts FOR ALL USING (true);
CREATE POLICY "Allow all access to approvals" ON public.approvals FOR ALL USING (true);
CREATE POLICY "Allow all access to reports" ON public.reports FOR ALL USING (true);
